### ISSUE TITLE
[cronet_http] - ClassNotFoundException when use cronet_http in isolate

### ISSUE THREAD

**Issue by lstonussi** [dart-lang/http#1092]
Hello,

I`m receiving following error everytime when use `cronet_http` in isolate:

```E/hy      (31611): Exception fetching LoggerImpl class
E/hy      (31611): java.lang.ClassNotFoundException: Didn't find class "com.google.net.cronet.telemetry.CronetLoggerImpl" on path: DexPathList[[zip file "/data/user_de/0/com.google.android.gms/app_chimera/m/0000033d/CronetDynamite.apk"],nativeLibraryDirectories=[/data/user_de/0/com.google.android.gms/app_chimera/m/0000033d/CronetDynamite.apk!/lib/arm64-v8a, /system/lib64]]
E/hy      (31611):     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
E/hy      (31611):     at dalvik.system.DelegateLastClassLoader.loadClass(DelegateLastClassLoader.java:137)
E/hy      (31611):     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/hy      (31611):     at org.chromium.net.impl.CronetUrlRequestContext.<init>(:com.google.android.gms.dynamite_cronetdynamite@234816031@23.48.16 (150400-0):90)
E/hy      (31611):     at org.chromium.net.impl.NativeCronetEngineBuilderImpl.build(:com.google.android.gms.dynamite_cronetdynamite@234816031@23.48.16 (150400-0):14)
E/hy      (31611):     at org.chromium.net.CronetEngine$Builder.build(CronetEngine.java:313)
```

Flutter version:
```
[✓] Flutter (Channel stable, 3.16.0, on macOS 13.1 22C65 darwin-arm64, locale
    en-BR)
    • Flutter version 3.16.0 on channel stable at /Users/suamusica/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (6 weeks ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2
```

package version: `cronet_http: 0.4.0-jni`

Can anyone tell me what's going on?

tks!

**Comment by brianquinlan** [comment]
We do have tests for using `package:cronet_http` in isolates.

Are you testing this using an Android emulator on macOS? What OS/Playstore versions are installed in the emulator?

**Comment by lstonussi** [comment]
I'm testing in real device, Samsung Galaxy S10 (SM G973F) Android 11
Playstore v38.7.32-29

**Comment by brianquinlan** [comment]
Could you try upgrading to version 1.0.0?

**Comment by atrope** [comment]
@brianquinlan Can you release 1.0.0 with jni? 
https://pub.dev/packages/cronet_http/versions/0.4.0-jni

**Comment by brianquinlan** [comment]
1.0.0 does use JNI

**Comment by lstonussi** [comment]
@brianquinlan
The same error occurs in version 1.0.0

**Comment by lstonussi** [comment]
@brianquinlan 
Do you have any update about this?

**Comment by brianquinlan** [comment]
I can't reproduce the issue so I don't know what steps I should take to fix it.

**Comment by HosseinYousefi** [comment]
@lstonussi Do you still face this issue? Could you share a minimal reproducible code example that fails?
