### ISSUE TITLE
ClientException with SocketException: Connection failed (OS Error: No route to host, errno = 65), address = 192.162.10.1, port = 2018, uri=http://192.162.10.1:2018/wiced_ota_server/ssid_chunk.html?ssid=Beah_bug&pwd=123456 

### ISSUE THREAD

**Issue by E2-Veera** [dart-lang/http#1278]
I've a flutter iOS app and WiFi IoT device.... I used to connect my mobile and IoT device using my flutter app, Then I have call one GET request to communicate with IoT device. Now the problem is that GET Api give me the following exception

1. Turn on the IOT device into pairing mode (IOT device start emitting a WiFi connection)
2. Connect to that IOT device's WiFi using flutter app
3. Call the GET API request to communicate to IOT device

> ClientException with SocketException: Connection failed (OS Error: No route to host, errno = 65), address = 192.168.10.1, port = 2018, uri=http://192.168.10.1:2018/wiced_ota_server/ssid_chunk.html?ssid=Beah_bug&pwd=djdjdjfjfjfjc 2
> 
> #0 IOClient.send (package:http/src/io_client.dart:154) #1 BaseClient._sendUnstreamed (package:http/src/base_client.dart:93) #2 _withClient (package:http/http.dart:167) #3 Future.timeout. (dart:async/future_impl.dart:940) #4 _NetworkSetupState.pushWiFiSettingsToBelt (package:aptbelt/WiFiConfiguration/networkSetupPage.dart:459)

Note : Mobile is connected to IoT device, IoT device doesn't have internet connection

GET request should properly work

I've checked the flow manually by connecting to IOT device and call the GET request using chrome.... It's working fine..... in Flutter iOS app it's not working

**Comment by ProSistemasDev** [comment]
Comigo aconteceu o mesmo problema, meu aplicativo tenta conectar a API local com IP 192.168.0.100 porta 8070 e não conecta, apenas ocorre o problema na versão publicada (release), debug funciona normalmente. 

Testando em outra rede com IP 192.168.254.100 funciona normalmente em todas as versões.

Alguém pode me ajudar?

**Comment by MattiaPispisa** [comment]
Hi @E2-Veera, I had the same issue on iOS. Did you include the NSLocalNetworkUsageDescription entry in your info.plist file (ios/Runner/Info.plist) ?
