### ISSUE TITLE
JniException  accessors.dart in JniAccessorWrappers.throwException in V1.3.2

### ISSUE THREAD

**Issue by escamoteur** [dart-lang/http#1303]
@HosseinYousefi

new JniException:

```
JniException: Exception in Java code called through JNI: java.lang.NullPointerException: Method is required.

java.lang.NullPointerException: Method is required.
	at j$.util.Objects.requireNonNull(SourceFile:2)
	at m.mg.setHttpMethod(:com.google.android.gms.dynamite_cronetdynamite@243333038@24.33.33 (190400-0):1)
	at m.mg.setHttpMethod(:com.google.android.gms.dynamite_cronetdynamite@243333038@24.33.33 (190400-0):2)
  #0      JniAccessorWrappers.throwException (package:jni/src/accessors.dart:119)
  #1      _check (package:jni/src/accessors.dart:11)
  #2      JniResultMethods.check (package:jni/src/accessors.dart:16)
  #3      JniResultMethods.objectPointer (package:jni/src/accessors.dart:54)
  #4      JniResultMethods.reference (package:jni/src/accessors.dart:59)
  #5      JniResultMethods.object (package:jni/src/accessors.dart:63)
  #6      UrlRequest_Builder.setHttpMethod (package:cronet_http/src/jni/jni_bindings.dart:3324)
  #7      CronetClient.send (package:cronet_http/src/cronet_client.dart:383)
  File "<asynchronous suspension>"
  #9      HttpFileService.get (package:flutter_cache_manager/src/web/file_service.dart:37)
  File "<asynchronous suspension>"
  #11      WebHelper._updateFile (package:flutter_cache_manager/src/web/web_helper.dart:96)
  File "<asynchronous suspension>"
  #13      WebHelper._downloadOrAddToQueue (package:flutter_cache_manager/src/web/web_helper.dart:64)
```

**Comment by brianquinlan** [comment]
@HosseinYousefi Any ideas?

**Comment by HosseinYousefi** [comment]
[`NewString`](https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/functions.html#NewString) used to convert Dart strings into Java strings is said to return `NULL` when "the string cannot be constructed" which is not that helpful.

I looked further into [ART implementation of `NewString`](https://cs.android.com/android/platform/superproject/main/+/main:art/runtime/jni/jni_internal.cc;l=1972-1984?q=jni_internal.cc) but didn't find anything that will obviously fail. Out of memory issues should throw an earlier exception as well. 

Do you have a reproducible example of this @escamoteur? Does this happen frequently?
