### ISSUE TITLE
Version `2.0.0` incompatible with iOS 15 & 16

### ISSUE THREAD

**Issue by jankuss** [dart-lang/http#1398]
After upgrading to version `2.0.0` of `cupertino_http`, we noticed the following error on our test devices running on iOS 15 and iOS 16.

Code:

```
void main() async {
  final client = CupertinoClient.defaultSessionConfiguration();
  final response = await client.get(Uri.parse("https://google.com"));
}
```

This will fail with the following exception:

```
      Exception: Failed to load method of Objective-C protocol
      #0      getProtocolMethodSignature (package:objective_c/src/internal.dart:70:5)
      #1      NSURLSessionDataDelegate.URLSession_didCreateTask_ (package:cupertino_http/src/native_cupertino_bindings.dart:66561:10)
      #2      NSURLSessionDataDelegate.URLSession_didCreateTask_ (package:cupertino_http/src/native_cupertino_bindings.dart)
      #3      NSURLSessionDataDelegate.addToBuilderAsListener (package:cupertino_http/src/native_cupertino_bindings.dart:66338:30)
      #4      URLSession.delegate (package:cupertino_http/src/cupertino_api.dart:853:34)
      #5      new URLSession.sessionWithConfiguration (package:cupertino_http/src/cupertino_api.dart:1066:13)
      #6      new CupertinoClient.fromSessionConfiguration (package:cupertino_http/src/cupertino_client.dart:240:32)
      #7      new CupertinoClient.defaultSessionConfiguration (package:cupertino_http/src/cupertino_client.dart:234:28)
```

Is this an intended breaking change? I could not find any mention of this in the release notes. As iOS 15 & 16 are still in use by many phones, I believe they should still be supported: https://iosref.com/ios-usage

We were able to resolve this issue by staying on `1.5.1` of `cupertino_http`. Will support of iOS 15 & 16 be dropped with future `cupertino_http` Versions >=2.0.0?

**Comment by brianquinlan** [comment]
I'm looking into this now.

**Comment by brianquinlan** [comment]
Could you try again with `cupertino_http` 2.0.1?

**Comment by jankuss** [comment]
thanks a lot for the quick fix! It is working now
