### ISSUE TITLE
Out-of-order callbacks received in cuperto_http

### ISSUE THREAD

**Issue by brianquinlan** [dart-lang/http#1413]
flutter: Null check operator used on a null value
flutter: #0      CupertinoClient._tracker (package:cupertino_http/src/cupertino_client.dart:165)
flutter: #1      CupertinoClient._onResponse (package:cupertino_http/src/cupertino_client.dart:224)
flutter: #2      URLSession.delegate.<anonymous closure> (package:cupertino_http/src/cupertino_api.dart:901)
flutter: #3      NSURLSessionDataDelegate.URLSession_dataTask_didReceiveResponse_completionHandler_.<anonymous closure>.<anonymous closure> (package:cupertino_http/src/native_cupertino_bindings.dart:65934)
flutter: #4      ObjCBlock_ffiVoid_ffiVoid_NSURLSession_NSURLSessionDataTask_NSURLResponse_ffiVoidNSURLSessionResponseDisposition.listener.<anonymous closure> (package:cupertino_http/src/native_cupertino_bindings.dart:60886)
flutter: #5      _ObjCBlock_ffiVoid_ffiVoid_NSURLSession_NSURLSessionDataTask_NSURLResponse_ffiVoidNSURLSessionResponseDisposition_listenerTrampoline (package:cupertino_http/src/native_cupertino_bindings.dart:60772)
flutter: #6      _ObjCBlock_ffiVoid_ffiVoid_NSURLSession_NSURLSessionDataTask_NSURLResponse_ffiVoidNSURLSessionResponseDisposition_listenerCallable.<anonymous closure> (package:cupertino_http/src/native_cupertino_bindings.dart)
flutter: #9      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:194)

**Comment by brianquinlan** [comment]
See https://github.com/dart-lang/native/issues/1760

**Comment by jankuss** [comment]
We also observe this with version `2.0.1`, when "Minimum Deployments" is set to iOS 16 for the Pods-project and the app is a release-build.
<img width="759" alt="image" src="https://github.com/user-attachments/assets/07dceebc-928d-47b2-81df-dedce02c4c1f">

The `future` will never resolve in this example, it will always show "Waiting":

```dart
import 'package:cupertino_http/cupertino_http.dart';
import 'package:flutter/material.dart';

void main() {
  final client = CupertinoClient.defaultSessionConfiguration();
  final a = client.get(Uri.parse('https://google.de'));

  runApp(
    MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        body: Center(
          child: FutureBuilder(
              future: a,
              builder: (context, response) {
                if (response.connectionState == ConnectionState.waiting) {
                  return const Text('Waiting');
                }

                return const Text('Done');
              }),
        ),
      ),
    ),
  );
}
```

**Comment by brianquinlan** [comment]
@jankuss Could you reproduce this on a debug build?

**Comment by jankuss** [comment]
I definetly saw the same trace back last week while debugging. Today I tried again, and I could not see the message in logs anymore. Might this be another issue?

My reproduction for the issue I am experiencing is located here: https://github.com/jankuss/cupertino_http_stuck_requests

**Important:** It needs to be built in **release mode** and run on a **real device**

Debug builds do not run into this issue. A notable change which I did not mention explicitly yet is the following adjustment in the Podfile:
```rb
/* ... */

 post_install do |installer|
   installer.pods_project.targets.each do |target|
     flutter_additional_ios_build_settings(target)
+    target.build_configurations.each do |config|
+      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
+    end
   end
 end
```

Let me know if this might be related, if not I will gladly create a separate issue.

**Comment by brianquinlan** [comment]
> Let me know if this might be related, if not I will gladly create a separate issue.

I think that the issue is related and I'm looking into it. It might take a while to sort this out.
