### ISSUE TITLE
iOS cupertino_http error: Unhandled Exception: Invalid argument(s): Couldn't resolve native function '_wrapListenerBlock_1a6kixf'

### ISSUE THREAD

**Issue by Shubham1993** [dart-lang/http#1417]
I am trying to run the sample app given with cupertino_http package in iOS. But I am getting below error.

`NSBundle file:///System/Library/PrivateFrameworks/MetalTools.framework/ principal class is nil because all fallbacks have failed
flutter: The Dart VM service is listening on http://127.0.0.1:53003/tmg2xds8gus=/
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Couldn't resolve native function '_wrapListenerBlock_1a6kixf' in 'package:cupertino_http/src/native_cupertino_bindings.dart' : No asset with id 'package:cupertino_http/src/native_cupertino_bindings.dart' found. No available native assets. Attempted to fallback to process lookup. dlsym(RTLD_DEFAULT, _wrapListenerBlock_1a6kixf): symbol not found.

#0      Native._ffi_resolver.#ffiClosure0 (dart:ffi-patch/ffi_patch.dart)
#1      Native._ffi_resolver_function (dart:ffi-patch/ffi_patch.dart:1523:20)
#2      _wrapListenerBlock_1a6kixf (package:cupertino_http/src/native_cupertino_bindings.dart)
#3      ObjCBlock_ffiVoid_ffiVoid_NSURLSession_NSURLSessionTask_NSError.listener (package:cupertino_http/src/native_cupertino_bindings.dart:65985:21)
#4      NSURLSessionDataDelegate.URLSession_task_didCompleteWithError_.<anonymous closure> (package:cupertino_http/src/native_cupertino_bindings.dart:66922:14)
#5      ObjCProtocolListenableMethod.implementAsListener (package:objective_c/src/protocol_builder.dart:80:69)
#6      URLSession.delegate (package:cupertino_http/src/cupertino_api.dart:854:10)
#7      new URLSession.sessionWithConfiguration (package:cupertino_http/src/cupertino_api.dart:1070:13)
#8      new CupertinoClient.fromSessionConfiguration (package:cupertino_http/src/cupertino_client.dart:240:32)
#9      main (package:cupertino_http_example/main.dart:23:34)
#10     _runMain.<anonymous closure> (dart:ui/hooks.dart:301:23)
#11     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#12     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)`

**Comment by Shubham1993** [comment]
@brianquinlan Yes, this issue is coming on cupertino_http 2.0.1. Below is output for flutter doctor -v.

```
[✓] Flutter (Channel stable, 3.24.5, on macOS 15.0.1 24A348 darwin-arm64, locale en-IN)
    • Flutter version 3.24.5 on channel stable at /Users/sgupta/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (4 weeks ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/to/macos-android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/macos-android-setup for detailed instructions).

[✓] VS Code (version 1.95.3)
    • VS Code at /Users/sgupta/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • iPhone 16 Pro (mobile)          • 1D91F2CF-1346-4494-8C48-FD150BB9CE92 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-18-1
      (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 15.0.1 24A348 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 15.0.1 24A348 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 131.0.6778.109
    ! Error: Browsing on the local area network for Mayank Rastogi iphone. Ensure the device is unlocked and attached with a cable or associated with
      the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Shubham’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the
      same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.
```

**Comment by brianquinlan** [comment]
@Shubham1993 And you are running this on a real iOS device (not the simulator) in debug mode (you could include the command used to run flutter)?

**Comment by brianquinlan** [comment]
@liamappelbe

**Comment by Shubham1993** [comment]
@brianquinlan I have tried running the app on simulator and real device both. On real device first i tried without debug mode and then in debug mode, but in each case getting same error.

for real device in debug mode i used command - flutter run -d {UUID}

**Comment by Shubham1993** [comment]
@liamappelbe I ran nm <some binary> | grep 'wrapListenerBlock_1a6kixf' command for multiple output files and dylibs, but it returned empty response.

```
nm /Users/user/Desktop/cupertino_http-2.0.1/example/build/ios/iphoneos/Runner.app/__preview.dylib  | grep 'wrapListenerBlock_1a6kixf'
nm /Users/user/Desktop/cupertino_http-2.0.1/example/build/ios/iphoneos/Runner.app/Runner  | grep 'wrapListenerBlock_1a6kixf'
nm /Users/user/Desktop/cupertino_http-2.0.1/example/build/ios/iphoneos/Runner.app/Frameworks/App.framework/App  | grep 'wrapListenerBlock_1a6kixf'
```

**Comment by dballance** [comment]
I was able to reproduce this - but the issue is probably somewhat related to the package directly.

For some other packages, the maintainer has quit including additional binaries in the pods, and is instead statically linking now to the SPM published version. 

They suggested the resolution as setting `use_frameworks! #:linkage => :static` - which caused this issue. Compilation was fine - but I got an error similar to this at runtime.

Figured the context might help - might appear more as packages move from CocoaPods to SPM over the next year or so.

**Comment by hlovingness** [comment]
Invalid argument(s): Couldn't resolve native function '_NativeCupertinoHttp_protocolTrampoline_1tz5yf' in 'package:cupertino_http/src/native_cupertino_bindings.dart' : No asset with id 'package:cupertino_http/src/native_cupertino_bindings.dart' found. Available native assets: package:objective_c/objective_c.dylib. Attempted to fallback to process lookup. dlsym(RTLD_DEFAULT, _NativeCupertinoHttp_protocolTrampoline_1tz5yf): symbol not found.

**Comment by ain-py** [comment]
we used flutter add to app setup and fixed it by adding this in podfile

  
```
  app_target_names = ['Release', 'Debug'] // change this to your app target 
  installer.aggregate_targets
  .flat_map(&:user_targets)
  .uniq
  .select { |target| app_target_names.include?(target.name) }
  .each do |target|
    target.build_configurations.each do |config|
      header_paths = Array(config.build_settings['HEADER_SEARCH_PATHS']).dup
      header_paths << '$(inherited)' unless header_paths.include?('$(inherited)')
      config.build_settings['HEADER_SEARCH_PATHS'] = header_paths
      
      ldflags = Array(config.build_settings['OTHER_LDFLAGS']).dup
      ldflags << '$(inherited)' unless ldflags.include?('$(inherited)')
      config.build_settings['OTHER_LDFLAGS'] = ldflags
    end
  end
  installer.aggregate_targets
  .map(&:user_project)
  .uniq
  .each(&:save)
```

**Comment by lubritto** [comment]
After a rollout on our side, we got 10k events for 10k unique users out of 10 million. Is there a chance users are only getting the issue once? That would explain why the number of events matches the number of unique users. I saw the suggestion from @ain-py , but is there any explanation about what is causing the error?

```
0  libobjc.A.dylib                0x144c objc_retain_x0 + 16
1  libobjc.A.dylib                0x144c objc_retain + 16
2  CoreFoundation                 0x19e514 -[__NSDictionaryM setObject:forKey:] + 320
3  objective_c                    0x9ea8 -[DOBJCDartProtocolBuilder implementMethod:withBlock:withTrampoline:withSignature:] + 33 (protocol.m:33)
4  App                            0x9530 stub CallNativeThroughSafepoint + 21808
5  App                            0xe32284 objc_msgSend_1s2gdyk.#ffiClosure210 + 37494 (objective_c_bindings_generated.dart:37494)
6  App                            0xe32128 DartProtocolBuilder$Methods|implementMethod + 1433 (objective_c_bindings_generated.dart:1433)
7  App                            0xe32030 ObjCProtocolBuilder.implementMethod + 40 (protocol_builder.dart:40)
8  App                            0xe31fa8 ObjCProtocolMethod.implementWithBlock + 130 (protocol_builder.dart:130)
9  App                            0xe31f30 ObjCProtocolListenableMethod.implementAsListener + 173 (protocol_builder.dart:173)
10 App                            0xe319c8 URLSession.delegate + 874 (cupertino_api.dart:874)
11 App                            0xe31554 new URLSession.sessionWithConfiguration + 1090 (cupertino_api.dart:1090)
12 App                            0xe314dc new CupertinoClient.fromSessionConfiguration + 317 (cupertino_client.dart:317)
13 App                            0xe31430 new NativeAdapter + 13 (cupertino_adapter.dart:13)
```

**Comment by henawey-t** [comment]
> After a rollout on our side, we got 10k events for 10k unique users out of 10 million. Is there a chance users are only getting the issue once? That would explain why the number of events matches the number of unique users. I saw the suggestion from [@ain-py](https://github.com/ain-py) , but is there any explanation about what is causing the error?
> 
> ```
> 0  libobjc.A.dylib                0x144c objc_retain_x0 + 16
> 1  libobjc.A.dylib                0x144c objc_retain + 16
> 2  CoreFoundation                 0x19e514 -[__NSDictionaryM setObject:forKey:] + 320
> 3  objective_c                    0x9ea8 -[DOBJCDartProtocolBuilder implementMethod:withBlock:withTrampoline:withSignature:] + 33 (protocol.m:33)
> 4  App                            0x9530 stub CallNativeThroughSafepoint + 21808
> 5  App                            0xe32284 objc_msgSend_1s2gdyk.#ffiClosure210 + 37494 (objective_c_bindings_generated.dart:37494)
> 6  App                            0xe32128 DartProtocolBuilder$Methods|implementMethod + 1433 (objective_c_bindings_generated.dart:1433)
> 7  App                            0xe32030 ObjCProtocolBuilder.implementMethod + 40 (protocol_builder.dart:40)
> 8  App                            0xe31fa8 ObjCProtocolMethod.implementWithBlock + 130 (protocol_builder.dart:130)
> 9  App                            0xe31f30 ObjCProtocolListenableMethod.implementAsListener + 173 (protocol_builder.dart:173)
> 10 App                            0xe319c8 URLSession.delegate + 874 (cupertino_api.dart:874)
> 11 App                            0xe31554 new URLSession.sessionWithConfiguration + 1090 (cupertino_api.dart:1090)
> 12 App                            0xe314dc new CupertinoClient.fromSessionConfiguration + 317 (cupertino_client.dart:317)
> 13 App                            0xe31430 new NativeAdapter + 13 (cupertino_adapter.dart:13)
> ```

@liamappelbe Here is the same reporting on Objective-C library: https://github.com/dart-lang/native/issues/3209

**Comment by liamappelbe** [comment]
@lubritto that error is unrelated to this issue. Please file a new issue with a repro case.
