### ISSUE TITLE
WebSocketException: Connection  not upgraded to websocket

### ISSUE THREAD

**Issue by austin047** [dart-lang/http#1665]
I am attempting to connect to a WebSocket API delivered via the AWS API gateway, currently,  I am able to establish a successful connection via PostMan and Python scripts ran from my local terminal, but when I attempt a connection with dart I keep getting this error of `WebSocketException: Connection was not upgraded to websocket` 

My code
```
main() async {
  final wsUrl = Uri.parse('wss://xxxxxxxxxx.execute-api.eu-west-1.amazonaws.com/qa');
  final channel = IOWebSocketChannel.connect(wsUrl);

  // await channel.ready;

  channel.stream.listen((message) {
    print(message);
    channel.sink.add('received!');
  });
}
```

Error: 
```
Unhandled exception:
WebSocketChannelException: WebSocketChannelException: WebSocketException: Connection to 'https://xxxxxxxxxx.execute-api.eu-west-1.amazonaws.com:0/qa#' was not upgraded to websocket
#0      new IOWebSocketChannel._withoutSocket.<anonymous closure> (package:web_socket_channel/io.dart:98:24)
dart-lang/http#1604      Stream.handleError.<anonymous closure> (dart:async/stream.dart:931:16)
dart-lang/web_socket_channel#2      _HandleErrorStream._handleError (dart:async/stream_pipe.dart:269:17)
dart-lang/web_socket_channel#3      _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:157:13)
dart-lang/http#1605      _RootZone.runBinaryGuarded (dart:async/zone.dart:1606:10)
dart-lang/web_socket_channel#5      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358:15)
dart-lang/web_socket_channel#6      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:376:7)
dart-lang/web_socket_channel#7      _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280:7)
dart-lang/web_socket_channel#8      _SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:788:19)
dart-lang/web_socket_channel#9      _StreamController._addError (dart:async/stream_controller.dart:666:7)
dart-lang/web_socket_channel#10     _RootZone.runBinaryGuarded (dart:async/zone.dart:1606:10)
dart-lang/web_socket_channel#11     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358:15)
dart-lang/web_socket_channel#12     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:376:7)
dart-lang/web_socket_channel#13     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280:7)
dart-lang/http#1606     _SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:788:19)
dart-lang/http#1607     _StreamController._addError (dart:async/stream_controller.dart:666:7)
dart-lang/http#1608     new Stream.fromFuture.<anonymous closure> (dart:async/stream.dart:253:18)
dart-lang/http#1609     _RootZone.runBinary (dart:async/zone.dart:1666:54)
dart-lang/web_socket_channel#18     _FutureListener.handleError (dart:async/future_impl.dart:177:22)
dart-lang/web_socket_channel#19     Future._propagateToListeners.handleError (dart:async/future_impl.dart:858:47)
dart-lang/web_socket_channel#20     Future._propagateToListeners (dart:async/future_impl.dart:879:13)
dart-lang/http#1610     Future._completeError (dart:async/future_impl.dart:655:5)
dart-lang/http#1611     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:745:7)
dart-lang/http#1612     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
dart-lang/http#1613     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
dart-lang/http#1614     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
dart-lang/http#1615     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:405:11)
dart-lang/web_socket_channel#27     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
dart-lang/web_socket_channel#28     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

```

Any help on this will be much appreciated

**Comment by suside** [comment]
For nginx those headers are
```
proxy_set_header      Upgrade $http_upgrade;
proxy_set_header      Connection $connection_upgrade;
```
however we are getting this error despite having them.
