### ISSUE TITLE
Newbie usage question

### ISSUE THREAD

**Issue by gmlewis** [dart-lang/http#190]
I'm trying to follow the documentation to make a POST request and the content body is not getting sent to my server. Can someone please help me figure out what I'm doing wrong?  I'm using `http: '^0.11.3'` and 
`Dart VM version: 2.0.0 (Unknown timestamp) on "linux_x64"`.

First, here is my python3 `socket_echo_server.py`:

```python 
import socket

host = ''
port = 5000
backlog = 5
size = 1024
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.bind((host,port))
s.listen(backlog)
while 1:
    client, address = s.accept()
    data = client.recv(size)
    if data:
        print(data)
        client.send(data)
    client.close()
```

Next is my Dart program:

```dart
import 'dart:convert';

import 'package:http/http.dart' as http;

import 'package:http_experiment/http_experiment.dart' as http_experiment;

const _defaultBaseURL = "http://localhost:5000";

main(List<String> arguments) {
  var client = new http.Client();
  client
      .post(_defaultBaseURL + '/v1/envs/',
          body: {'name': 'doodle', 'color': 'blue'})
      .then((response) => print(response.body))
      .whenComplete(client.close);
}
```

When I run this, the Python echo server says:

> b'POST /v1/envs/ HTTP/1.1\r\nuser-agent: Dart/2.0 (dart:io)\r\ncontent-type: application/x-www-form-urlencoded; charset=utf-8\r\naccept-encoding: gzip\r\ncontent-length: 22\r\nhost: localhost:5000\r\n\r\n'

Note how the body content isn't included at the end.

As a sanity test, I ran a Go client to the Python echo server, and got the content at the end:

> b'POST /v1/envs/ HTTP/1.1\r\nHost: localhost:5000\r\nUser-Agent: Go-http-client/1.1\r\nContent-Length: 24\r\nContent-Type: application/json\r\nAccept-Encoding: gzip\r\n\r\n{"env_id":"CartPole-v0"}'

Any ideas what I'm doing wrong?

**Comment by gmlewis** [comment]
Even trying just the `dart:io` `HttpClient` gives the same results!

```dart
import 'dart:convert';
import 'dart:io';

main(List<String> arguments) {
  var client = HttpClient();
  client
      .post('localhost', 5000, '/v1/envs/')
      .then((request) {
        var body = jsonEncode({'name': 'doodle', 'color': 'blue'});
        request.headers.contentType =
            new ContentType('application', 'json', charset: 'utf-8');
        request.write(body);
        return request.close();
      })
      .then((response) => print(response))
      .whenComplete(client.close);
}
```

> b'POST /v1/envs/ HTTP/1.1\r\nuser-agent: Dart/2.0 (dart:io)\r\ncontent-type: application/json; charset=utf-8\r\ntransfer-encoding: chunked\r\naccept-encoding: gzip\r\nhost: localhost:5000\r\n\r\n'

Is something wrong with my Dart 2.0 installation?!?

**Comment by drbcode** [comment]
python server is reading it as `"content-type: application/x-www-form-urlencoded"` so it doesn't work
go server is reading it as `content-type: application/json; charset=utf-8` it works.

add "content-type: application/x-www-form-urlencoded;" header to http request and it will work for python client.
If you are developing it for the web then don't use "dart:io" otherwise use "dart:io"

**Comment by gmlewis** [comment]
Thank you, @drbcode, but that still doesn't work.  Here is the new Dart version:

```dart
import 'dart:convert';

import 'package:http/http.dart' as http;

import 'package:http_experiment/http_experiment.dart' as http_experiment;

const _defaultBaseURL = "http://localhost:5000";

main(List<String> arguments) {
  var client = new http.Client();
  client
      .post(_defaultBaseURL + '/v1/envs/',
          headers: {'content-type': 'application/json'},
          body: jsonEncode({'name': 'doodle', 'color': 'blue'}))
      .then((response) => print(response.body))
      .whenComplete(client.close);
}
```

and here is the new Python output:

> b'POST /v1/envs/ HTTP/1.1\r\nuser-agent: Dart/2.0 (dart:io)\r\ncontent-type: application/json; charset=utf-8\r\naccept-encoding: gzip\r\ncontent-length: 32\r\nhost: localhost:5000\r\n\r\n'

**Comment by drbcode** [comment]
use 'postFormData' method.

**Comment by drbcode** [comment]
you need to remove 'jsonEncode' to post it as a form data.

**Comment by gmlewis** [comment]
If I remove `jsonEncode`, I get a runtime error:

```
Unhandled exception:
Bad state: Cannot set the body fields of a Request with content-type "application/json".
#0      Request.bodyFields= (package:http/src/request.dart:124:7)
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:165:17)
<asynchronous suspension>
#2      BaseClient.post (package:http/src/base_client.dart:56:5)
#3      main (file:///home/glenn/src/http-experiment/bin/main.dart:14:8)
#4      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:277:32)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

**Comment by gmlewis** [comment]
I've reduced the Dart program down the the bare minimum and it still fails:

```dart
import 'dart:convert';

import 'package:http/http.dart' as http;

main(List<String> arguments) {
  http.post('http://localhost:5000/v1/envs/',
      body: json.encode({'color': 'blue'}));
}
```

> b'POST /v1/envs/ HTTP/1.1\r\nuser-agent: Dart/2.0 (dart:io)\r\ncontent-type: text/plain; charset=utf-8\r\naccept-encoding: gzip\r\ncontent-length: 16\r\nhost: localhost:5000\r\n\r\n'

Bizarre that the Go client works and Dart client fails. I'm going to try rebooting my machine.

**Comment by drbcode** [comment]
dart client:
```dart
import 'dart:async';
import 'package:http/http.dart';
import 'dart:html' as html;

class GlobalService {
  // for logging data to console
  void Log(dynamic m) {
    html.window.console.log(m);
  }
  final Client _http;
  GlobalService(this._http);
  static final _headers = {'Content-Type': 'application/x-www-form-urlencoded'};
  Future sendAjax(Map<String, String> data, url2) async {
    try {
      final response = await _http.post(url2, headers: _headers, body: data);
      return response;
    } catch (e) {
      throw _handleError(e);
    }
  }
  Exception _handleError(dynamic e) {
    Log(e); // for demo purposes only
    return new Exception('Server error; cause: $e');
  }
}
void main()async{
  var client=new Client();
  GlobalService g=new GlobalService(client);
  var a=new Map<String, String>();
  a["hello"]="hi";
  await g.sendAjax(a,"/any_url");
}
```

go server:
```go
import (
	"net/http"
	"strings"
)

// APILicenseValidationHandler is for validating license keys
func ExapmleHandler(w http.ResponseWriter, r *http.Request) {
	// request path is valid
	if r.Method != http.MethodPost {
		// invalid method
		return
	}
	// parse form data for processing
	err := r.ParseForm()
	if err != nil {
		// can't parse form
		w.Write([]byte("can't parse form"))
		return
	}
	var hello = strings.Join(r.Form["hello"], "")
	hello = strings.TrimSpace(hello)
	w.Write([]byte(hello))
	return
}
```

**Comment by gmlewis** [comment]
Thank you, @drbcode! I tried your Dart client and it still fails for me:

> b'POST /v1/envs/ HTTP/1.1\r\nuser-agent: Dart/2.0 (dart:io)\r\ncontent-type: application/x-www-form-urlencoded; charset=utf-8\r\naccept-encoding: gzip\r\ncontent-length: 8\r\nhost: localhost:5000\r\n\r\n'

Note how the `content-length` is 8, but no bytes are sent after the `\r\n\r\n`.

What does `dart --version` say on your machine?

Mine says: `Dart VM version: 2.0.0 (Unknown timestamp) on "linux_x64"`

**Comment by drbcode** [comment]
main.go
run with 
`go run main.go`
```go
package main

import (
	"net/http"
	"strings"

)

// APILicenseValidationHandler is for validating license keys
func ExapmleHandler(w http.ResponseWriter, r *http.Request) {
	// request path is valid
	if r.Method != http.MethodPost {
		// invalid method
		return
	}
	// parse form data for processing
	err := r.ParseForm()
	if err != nil {
		// can't parse form
		w.Write([]byte("can't parse form"))
		return
	}
	var hello = strings.Join(r.Form["hello"], "")
	hello = strings.TrimSpace(hello)
	w.Write([]byte(hello))
	return
}

func main()  {
	http.HandleFunc("/", ExapmleHandler)
	if err := http.ListenAndServe(":8086", nil); err != nil {
		panic(err)
	}
}
```
Dart client:
main.dart
```dart
import 'package:http/http.dart';
import 'dart:async';

class GlobalService {
  // for logging data to console
  void Log(dynamic m) {
    print(m);
  }
  final Client _http;
  GlobalService(this._http);
  static final _headers = {'Content-Type': 'application/x-www-form-urlencoded'};
  Future<Response> sendAjax(Map<String, String> data, url2) async {
    try {
      final response = await _http.post(url2, headers: _headers, body: data);
      return response;
    } catch (e) {
      throw _handleError(e);
    }
  }
  Exception _handleError(dynamic e) {
    Log(e); // for demo purposes only
    return new Exception('Server error; cause: $e');
  }
}
void sendReq()async{
  var client=new Client();
  GlobalService g=new GlobalService(client);
  var a=new Map<String, String>();
  a["hello"]="hi";
  var resp=await g.sendAjax(a,"http://localhost:8086/");
  print(resp.body);
}

main(List<String> arguments) async{
  sendReq();
}


```

**Comment by gmlewis** [comment]
That gave me a working example.  Thank you, @drbcode!!!
Closing.
