### ISSUE TITLE
Redirect loop detected

### ISSUE THREAD

**Issue by guiesteves** [dart-lang/http#192]
i have the following code in dart

```
import 'dart:io';
import 'package:http/http.dart' as http;

main() async {
  final url = 'https://jsonplaceholder.typicode.com/users';
  final response = await http.get(url);

  if (response.statusCode == HttpStatus.ok) {
    print(response.body);
  }
}
```
it works correctly, but when I change the query url to http://loterias.caixa.gov.br/wps/portal/loterias/landing/lotofacil/!ut/p/a1/04_Sj9CPykssy0xPLMnMz0vMAfGjzOLNDH0MPAzcDbz8vTxNDRy9_Y2NQ13CDA0sTIEKIoEKnN0dPUzMfQwMDEwsjAw8XZw8XMwtfQ0MPM2I02-AAzgaENIfrh-FqsQ9wBmoxN_FydLAGAgNTKEK8DkRrACPGwpyQyMMMj0VAcySpRM!/dl5/d5/L2dBISEvZ0FBIS9nQSEh/pw/Z7_61L0H0G0J0VSC0AC4GLFAD2003/res/id=buscaResultado/c=cacheLevelPage/=/?timestampAjax=1534624870817&concurso=1703

```
import 'dart:io';
import 'package:http/http.dart' as http;

main() async {
  final url =
      'http://loterias.caixa.gov.br/wps/portal/loterias/landing/lotofacil/!ut/p/a1/04_Sj9CPykssy0xPLMnMz0vMAfGjzOLNDH0MPAzcDbz8vTxNDRy9_Y2NQ13CDA0sTIEKIoEKnN0dPUzMfQwMDEwsjAw8XZw8XMwtfQ0MPM2I02-AAzgaENIfrh-FqsQ9wBmoxN_FydLAGAgNTKEK8DkRrACPGwpyQyMMMj0VAcySpRM!/dl5/d5/L2dBISEvZ0FBIS9nQSEh/pw/Z7_61L0H0G0J0VSC0AC4GLFAD2003/res/id=buscaResultado/c=cacheLevelPage/=/?timestampAjax=1534624870817&concurso=1703';
  final response = await http.get(url);

  if (response.statusCode == HttpStatus.ok) {
    print(response.body);
  }
}
```
the following error occurs

```
Unhandled exception:
Redirect loop detected
#0      IOClient.send (package:http/src/io_client.dart:64:7)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:171:38)
<asynchronous suspension>
#2      BaseClient.get (package:http/src/base_client.dart:34:5)
#3      get.<anonymous closure> (package:http/http.dart:47:34)
#4      _withClient (package:http/http.dart:167:20)
<asynchronous suspension>
#5      get (package:http/http.dart:47:3)
```

when I use the browser it works fine

**Comment by zoechi** [comment]
I answered that in https://stackoverflow.com/questions/51912621/redirect-loop-detected-dart

**Comment by cskau-g** [comment]
As per @zoechi's answer (thanks!) this does not seem to be a `http` issue - closing.
