### ISSUE TITLE
Throws exception 'Failed to parse header value'

### ISSUE THREAD

**Issue by sleith** [dart-lang/http#225]
Hi,

> Http lib version 0.12.0+1
> Flutter 1.0.0 • channel beta • https://github.com/flutter/flutter.git
> Framework • revision 5391447fae (6 weeks ago) • 2018-11-29 19:41:26 -0800
> Engine • revision 7375a0f414
> Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

I tried http.get(). It works fine on response code 200.
But when my server returns 401 Unauthorized, it throws exception "Failed to parse header value".
Please find the header below i got from Postman:

> Date →Fri, 11 Jan 2019 10:04:09 GMT
> Server →kong/0.11.2
> Content-Type →application/json; charset=utf-8
> WWW-Authenticate →Bearer realm="service" error="invalid_token" error_description="The access token is invalid or has expired"
> Vary →Accept-Encoding
> Content-Encoding →gzip
> Content-Length →97
> Keep-Alive →timeout=15, max=100
> Connection →Keep-Alive

Any idea why it failed parse header value?
Thank you

**Comment by zoechi** [comment]
Can you please post the full exception output?

**Comment by sleith** [comment]
Hi,
i print(exception) only show that text "Failed to parse header value".
Here's the code and url you can try to see this issue:

```
Future<http.Response> testHit() async {
    Map<String, String> headers = new Map<String, String>();
    headers['Content-Type'] = "application/json";
    headers['Accept'] = "application/json";
    headers['nik'] = "1805304321";
    headers['deviceNumber'] = "869058030276537";
    headers['role'] = "SALES_AGENT";
    headers['Authorization'] = "Bearer dXKCloWJ0KQp05nQSbfmj6EvO6sILGB5}";

    http.Response response;
    try {
      response = await http.get(
          "https://api-uat.homecredit.co.id/smart-headline/v1/headline/",
          headers: headers);
      longPrint("--> Requeststatus: " + response.statusCode.toString());

      if (response.statusCode == 200) {
        longPrint("->" + response.body);
        return response;
      } else {
        print("->Request failed with status:" + response.statusCode.toString());
      }
    } catch (exception) {
      print(exception);
      if (response != null) {
        print("Request failed with status: " + response.statusCode.toString());
      } else {
        print("response null");
      }
    }
    return null;
  }
```

If you run on postman it will give output.
Thank you :)

**Comment by sleith** [comment]
Hi,
Please find the log:

> E/flutter (15005): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
> E/flutter (15005): Failed to parse header value
> E/flutter (15005): #0      IOClient.send (package:http/src/io_client.dart:65:7)
> E/flutter (15005): <asynchronous suspension>
> E/flutter (15005): #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:169:38)
> E/flutter (15005): <asynchronous suspension>
> E/flutter (15005): #2      BaseClient.get (package:http/src/base_client.dart:32:7)
> E/flutter (15005): #3      get.<anonymous closure> (package:http/http.dart:46:36)
> E/flutter (15005): #4      _withClient (package:http/http.dart:166:20)
> E/flutter (15005): <asynchronous suspension>
> E/flutter (15005): #5      get (package:http/http.dart:46:5)
> E/flutter (15005): #6      LoginState.testHit (package:smart/screens/login/login_screen.dart:707:22)

Thank you

**Comment by zoechi** [comment]
Looks like this is an error your server causes

```
WWW-Authenticate →Bearer realm="service" error="invalid_token" error_description="The access token is invalid or has expired"
```

**Comment by annalaufey** [comment]
I have the same problem, I would love to know if you've found a solution. 
I know the reason is that my auth token is invalid, but I need to be able to catch the 401 unauthorized error when that happens. Instead it throws a parse header value error

**Comment by redvg** [comment]
Im having the same issue. Im trying to access the file which i've uploaded to firebase storage. So i've tried both .getDownloadURL() on the ref AND generating signed url on the gcs blob myself. It fails with 'invalid header field name' when using CachedNetworkImage() or Image.network(). When I try to use http.get() on it fails with the following 


E/flutter (23764): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhand
led exception:
E/flutter (23764): Invalid header field name
E/flutter (23764): #0      IOClient.send (package:http/src/io_client.dart:65:7)
E/flutter (23764): <asynchronous suspension>
E/flutter (23764): #1      BaseClient._sendUnstreamed (package:http/src/base_cli
ent.dart:169:38)
E/flutter (23764): <asynchronous suspension>
E/flutter (23764): #2      BaseClient.get (package:http/src/base_client.dart:32:
7)
E/flutter (23764): #3      get.<anonymous closure> (package:http/http.dart:46:36
)
E/flutter (23764): #4      _withClient (package:http/http.dart:166:20)
E/flutter (23764): <asynchronous suspension>
E/flutter (23764): #5      get (package:http/http.dart:46:5)
E/flutter (23764): #6      RecordCard.build (package:tishup/screens/feed/compone
nts/record_card/record_card.dart:53:7)
E/flutter (23764): #7      StatelessElement.build (package:flutter/src/widgets/f
ramework.dart:3774:28)
E/flutter (23764): #8      ComponentElement.performRebuild (package:flutter/src/
widgets/framework.dart:3721:15)
E/flutter (23764): #9      Element.rebuild (package:flutter/src/widgets/framewor
k.dart:3547:5)
E/flutter (23764): #10     ComponentElement._firstBuild (package:flutter/src/wid
gets/framework.dart:3701:5)
E/flutter (23764): #11     ComponentElement.mount (package:flutter/src/widgets/f
ramework.dart:3696:5)
E/flutter (23764): #12     Element.inflateWidget (package:flutter/src/widgets/fr
amework.dart:2950:14)
E/flutter (23764): #13     Element.updateChild (package:flutter/src/widgets/fram
ework.dart:2753:12)
E/flutter (23764): #14     SingleChildRenderObjectElement.mount (package:flutter
/src/widgets/framework.dart:4860:14)
E/flutter (23764): #15     Element.inflateWidget (package:flutter/src/widgets/fr
amework.dart:2950:14)
E/flutter (23764): #16     Element.updateChild (package:flutter/src/widgets/fram
ework.dart:2753:12)
E/flutter (23764): #17     SingleChildRenderObjectElement.mount (package:flutter
/src/widgets/framework.dart:4860:14)
E/flutter (23764): #18     Element.inflateWidget (package:flutter/src/widgets/fr
amework.dart:2950:14)
E/flutter (23764): #19     Element.updateChild (package:flutter/src/widgets/fram
ework.dart:2753:12)
E/flutter (23764): #20     ComponentElement.performRebuild (package:flutter/src/
widgets/framework.dart:3732:16)
E/flutter (23764): #21     Element.rebuild (package:flutter/src/widgets/framewor
k.dart:3547:5)
E/flutter (23764): #22     ComponentElement._firstBuild (package:flutter/src/wid
gets/framework.dart:3701:5)
E/flutter (23764): #23     ComponentElement.mount (package:flutter/src/widgets/f
ramework.dart:3696:5)
E/flutter (23764): #24     Element.inflateWidget (package:flutter/src/widgets/fr
amework.dart:2950:14)
E/flutter (23764): #25     Element.updateChild (package:flutter/src/widgets/fram
ework.dart:2753:12)
E/flutter (23764): #26     ComponentElement.performRebuild (package:flutter/src/
widgets/framework.dart:3732:16)
E/flutter (23764): #27     Element.rebuild (package:flutter/src/widgets/framewor
k.dart:3547:5)
E/flutter (23764): #28     ComponentElement._firstBuild (package:flutter/src/wid
gets/framework.dart:3701:5)
E/flutter (23764): #29     ComponentElement.mount (package:flutter/src/widgets/f
ramework.dart:3696:5)
E/flutter (23764): #30     ParentDataElement.mount (package:flutter/src/widgets/
framework.dart:4047:11)
E/flutter (23764): #31     Element.inflateWidget (package:flutter/src/widgets/fr
amework.dart:2950:14)
E/flutter (23764): #32     Element.updateChild (package:flutter/src/widgets/fram
ework.dart:2753:12)
E/flutter (23764): #33     ComponentElement.performRebuild (package:flutter/src/
widgets/framework.dart:3732:16)
E/flutter (23764): #34     Element.rebuild (package:flutter/src/widgets/framewor
k.dart:3547:5)
E/flutter (23764): #35     ComponentElement._firstBuild (package:flutter/src/wid
gets/framework.dart:3701:5)
E/flutter (23764): #36     StatefulElement._firstBuild (package:flutter/src/widg
ets/framework.dart:3848:11)
E/flutter (23764): #37     ComponentElement.mount (package:flutter/src/widgets/f
ramework.dart:3696:5)
E/flutter (23764): #38     Element.inflateWidget (package:flutter/src/widgets/fr
amework.dart:2950:14)
E/flutter (23764): #39     Element.updateChild (package:flutter/src/widgets/fram
ework.dart:2753:12)
E/flutter (23764): #40     SliverMultiBoxAdaptorElement.updateChild (package:flu
tter/src/widgets/sliver.dart:1028:36)
E/flutter (23764): #41     SliverMultiBoxAdaptorElement.createChild.<anonymous c
losure> (package:flutter/src/widgets/sliver.dart:1013:20)
E/flutter (23764): #42     BuildOwner.buildScope (package:flutter/src/widgets/fr
amework.dart:2266:19)
E/flutter (23764): #43     SliverMultiBoxAdaptorElement.createChild (package:flu
tter/src/widgets/sliver.dart:1006:11)
E/flutter (23764): #44     RenderSliverMultiBoxAdaptor._createOrObtainChild.<ano
nymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:274
:23)
E/flutter (23764): #45     RenderObject.invokeLayoutCallback.<anonymous closure>
 (package

**Comment by redvg** [comment]
Im having the same issue. Im trying to access the file which i've uploaded to firebase storage. So i've tried both .getDownloadURL() on the ref AND generating signed url on the gcs blob myself. It fails with 'invalid header field name' when using CachedNetworkImage() or Image.network(). When I try to use http.get() on it fails with the following 


E/flutter (23764): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhand
led exception:
E/flutter (23764): Invalid header field name
E/flutter (23764): #0      IOClient.send (package:http/src/io_client.dart:65:7)
E/flutter (23764): <asynchronous suspension>
E/flutter (23764): #1      BaseClient._sendUnstreamed (package:http/src/base_cli
ent.dart:169:38)
E/flutter (23764): <asynchronous suspension>
E/flutter (23764): #2      BaseClient.get (package:http/src/base_client.dart:32:
7)
E/flutter (23764): #3      get.<anonymous closure> (package:http/http.dart:46:36
)
E/flutter (23764): #4      _withClient (package:http/http.dart:166:20)
E/flutter (23764): <asynchronous suspension>
E/flutter (23764): #5      get (package:http/http.dart:46:5)
E/flutter (23764): #6      RecordCard.build (FOO/screens/feed/compone
nts/record_card/record_card.dart:53:7)
E/flutter (23764): #7      StatelessElement.build (package:flutter/src/widgets/f
ramework.dart:3774:28)
E/flutter (23764): #8      ComponentElement.performRebuild (package:flutter/src/
widgets/framework.dart:3721:15)
E/flutter (23764): #9      Element.rebuild (package:flutter/src/widgets/framewor
k.dart:3547:5)
E/flutter (23764): #10     ComponentElement._firstBuild (package:flutter/src/wid
gets/framework.dart:3701:5)
E/flutter (23764): #11     ComponentElement.mount (package:flutter/src/widgets/f
ramework.dart:3696:5)
E/flutter (23764): #12     Element.inflateWidget (package:flutter/src/widgets/fr
amework.dart:2950:14)
E/flutter (23764): #13     Element.updateChild (package:flutter/src/widgets/fram
ework.dart:2753:12)
E/flutter (23764): #14     SingleChildRenderObjectElement.mount (package:flutter
/src/widgets/framework.dart:4860:14)
E/flutter (23764): #15     Element.inflateWidget (package:flutter/src/widgets/fr
amework.dart:2950:14)
E/flutter (23764): #16     Element.updateChild (package:flutter/src/widgets/fram
ework.dart:2753:12)
E/flutter (23764): #17     SingleChildRenderObjectElement.mount (package:flutter
/src/widgets/framework.dart:4860:14)
E/flutter (23764): #18     Element.inflateWidget (package:flutter/src/widgets/fr
amework.dart:2950:14)
E/flutter (23764): #19     Element.updateChild (package:flutter/src/widgets/fram
ework.dart:2753:12)
E/flutter (23764): #20     ComponentElement.performRebuild (package:flutter/src/
widgets/framework.dart:3732:16)
E/flutter (23764): #21     Element.rebuild (package:flutter/src/widgets/framewor
k.dart:3547:5)
E/flutter (23764): #22     ComponentElement._firstBuild (package:flutter/src/wid
gets/framework.dart:3701:5)
E/flutter (23764): #23     ComponentElement.mount (package:flutter/src/widgets/f
ramework.dart:3696:5)
E/flutter (23764): #24     Element.inflateWidget (package:flutter/src/widgets/fr
amework.dart:2950:14)
E/flutter (23764): #25     Element.updateChild (package:flutter/src/widgets/fram
ework.dart:2753:12)
E/flutter (23764): #26     ComponentElement.performRebuild (package:flutter/src/
widgets/framework.dart:3732:16)
E/flutter (23764): #27     Element.rebuild (package:flutter/src/widgets/framewor
k.dart:3547:5)
E/flutter (23764): #28     ComponentElement._firstBuild (package:flutter/src/wid
gets/framework.dart:3701:5)
E/flutter (23764): #29     ComponentElement.mount (package:flutter/src/widgets/f
ramework.dart:3696:5)
E/flutter (23764): #30     ParentDataElement.mount (package:flutter/src/widgets/
framework.dart:4047:11)
E/flutter (23764): #31     Element.inflateWidget (package:flutter/src/widgets/fr
amework.dart:2950:14)
E/flutter (23764): #32     Element.updateChild (package:flutter/src/widgets/fram
ework.dart:2753:12)
E/flutter (23764): #33     ComponentElement.performRebuild (package:flutter/src/
widgets/framework.dart:3732:16)
E/flutter (23764): #34     Element.rebuild (package:flutter/src/widgets/framewor
k.dart:3547:5)
E/flutter (23764): #35     ComponentElement._firstBuild (package:flutter/src/wid
gets/framework.dart:3701:5)
E/flutter (23764): #36     StatefulElement._firstBuild (package:flutter/src/widg
ets/framework.dart:3848:11)
E/flutter (23764): #37     ComponentElement.mount (package:flutter/src/widgets/f
ramework.dart:3696:5)
E/flutter (23764): #38     Element.inflateWidget (package:flutter/src/widgets/fr
amework.dart:2950:14)
E/flutter (23764): #39     Element.updateChild (package:flutter/src/widgets/fram
ework.dart:2753:12)
E/flutter (23764): #40     SliverMultiBoxAdaptorElement.updateChild (package:flu
tter/src/widgets/sliver.dart:1028:36)
E/flutter (23764): #41     SliverMultiBoxAdaptorElement.createChild.<anonymous c
losure> (package:flutter/src/widgets/sliver.dart:1013:20)
E/flutter (23764): #42     BuildOwner.buildScope (package:flutter/src/widgets/fr
amework.dart:2266:19)
E/flutter (23764): #43     SliverMultiBoxAdaptorElement.createChild (package:flu
tter/src/widgets/sliver.dart:1006:11)
E/flutter (23764): #44     RenderSliverMultiBoxAdaptor._createOrObtainChild.<ano
nymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:274
:23)
E/flutter (23764): #45     RenderObject.invokeLayoutCallback.<anonymous closure>
 (package

**Comment by redvg** [comment]
so I found the reason: I was attaching EXIF tags to the image metadata which gcs attaches to the response headers:). implications for http lib might be:  
.it has to learn to parse exotic headers
.it has to provide a meaningful error info, like which header field it fails to process

**Comment by karoitay** [comment]
Another way to repro

```dart
import 'package:http/http.dart' as http;

main() async {
  await http.post("https://api.thetvdb.com/login");
}
```

Exception:
```
Unhandled exception:
Failed to parse header value
#0      IOClient.send (package:http/src/io_client.dart:65:7)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:169:38)
<asynchronous suspension>
#2      BaseClient.post (package:http/src/base_client.dart:54:7)
#3      post.<anonymous closure> (package:http/http.dart:70:16)
#4      _withClient (package:http/http.dart:166:20)
<asynchronous suspension>
#5      post (package:http/http.dart:69:5)
#6      main (file:///usr/local/google/home/karoitay/Desktop/dart2/example/dart2_example.dart:4:9)
<asynchronous suspension>
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

Result of `curl -i -X POST https://api.thetvdb.com/login`:
```
HTTP/2 401 
date: Mon, 29 Jul 2019 09:15:50 GMT
content-type: application/json; charset=utf-8
content-length: 26
set-cookie: __cfduid=d0a0c5ee3934fe0f08c3ddd136ab53e471564391749; expires=Tue, 28-Jul-20 09:15:49 GMT; path=/; domain=.thetvdb.com; HttpOnly
vary: Accept-Language
www-authenticate: JWT realm=jwt auth
x-powered-by: Thundar!
x-thetvdb-api-version: 2.2.0
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 4fddfd9498b5c2c2-FRA

{"Error":"Not authorized"}
```

Looks like parsing of `www-authenticate: JWT realm=jwt auth` fails because of the space after `realm=jwt`.
Not sure if this is a valid header, but regardless, I think that callers should be able to get the 401 response and handle it instead.

**Comment by Andranjo97** [comment]
Hey guys so in case you are getting this error and assigning your response to a `final`, then change it to be `var`. That worked for me.

**Comment by jgrandchavin** [comment]
Same error for me, I have 2 different env and it works with one but not the other (I get Failed to parse header error)

**Comment by liudonghua123** [comment]
I have a similar issue https://github.com/dart-lang/pub/issues/2658.

**Comment by marioki** [comment]
Any solution to this error? Im having the same issue. 
I found this but i have no idea what it means.

https://github.com/flutterchina/dio/issues/219#issuecomment-472797390

**Comment by rvowles** [comment]
The immediate fix would be to not use inline enums. I'll have time to
resolve it specifically close to Xmas when I can't take done time of but
I'm too busy right now sorry.

**Comment by abhaysood** [comment]
I'm facing the same issue. For 401s a server I need to interact with responds with the header:
`WWW-Authenticate: Bearer realm=<realm_value>, error=invalid-token, error_description=Invalid bearer token`

This fails with an exception `HttpException: Failed to parse header value` which makes it really hard to handle refresh token scenarios. I think it happens because of the spaces in header value. 

I don't think the HTTP RFC mentions any format for the value in the `WWW-Authenticate` header. [Ref](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.8).

Can this be prioritised anytime soon? Happy to help in contributing if I can get some guidance.

**Comment by objectivecosta** [comment]
Also happens when you receive a header with an empty value... Eg.:

```
< date: Tue, 22 Jun 2021 14:21:40 GMT
< content-type: application/json;charset=UTF-8
**< access-control-expose-headers:** 
< access-control-allow-origin: *
< vary: accept-encoding
< access-control-allow-methods: GET
< accept-encoding: application/json
< access-control-allow-headers: authorization,Access-Control-Allow-Origin,Content-Type,SOAPAction,Authorization,Authorization
```

The highlighted headers seem to break the http package.

**Comment by natebosch** [comment]
This appears to be a problem in the SDK. I can reproduce this with

```dart
import 'dart:io';

void main() async {
  var client = HttpClient();
  var request =
      await client.openUrl('POST', Uri.parse('https://api.thetvdb.com/login'));
  var response = await request.close();
  await response.drain();
  client.close();
}
```
