### ISSUE TITLE
Occasionally blank exception text

### ISSUE THREAD

**Issue by ozzy1873** [dart-lang/http#284]
Occasionally a ClientException is thrown with no error message, which makes debugging difficult. My app has an error handler which catches the exception with onError: (error, stackTrace). The stack trace is always there, but the error parameter is sometimes blank. I have not been able to replicate the error myself, but I get several error reports each day. How should this exception be handled?

The stack trace is always:
#0      IOClient.send (package:http/src/io_client.dart:65)
<asynchronous suspension>
#1      RetryClient.send (package:http_retry/http_retry.dart:97)
<asynchronous suspension>
#2      BaseClient._sendUnstreamed (package:http/src/base_client.dart:169)
<asynchronous suspension>
#3      BaseClient.post (package:http/src/base_client.dart:54)
...or...
#3      BaseClient.get (package:http/src/base_client.dart:32)

**Comment by cskau-g** [comment]
Looking at the `io_client.dart` code I don't see any obvious cause of empty errors like that.
My best guess based on nothing else would be that something with the connection or response is malfunctioning.

Do you have some minimal example code showing how this is triggered?

Thanks.

**Comment by troncomputers** [comment]
I have similar or even same error.
```
E/flutter (27875): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: 
E/flutter (27875): #0      IOClient.send (package:http/src/io_client.dart:65:7)
E/flutter (27875): <asynchronous suspension>
E/flutter (27875): #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:169:38)
E/flutter (27875): <asynchronous suspension>
E/flutter (27875): #2      BaseClient.post (package:http/src/base_client.dart:54:7)
E/flutter (27875): #3      post.<anonymous closure> (package:http/http.dart:70:16)
E/flutter (27875): #4      _withClient (package:http/http.dart:166:20)
E/flutter (27875): <asynchronous suspension>
E/flutter (27875): #5      post (package:http/http.dart:69:5)
E/flutter (27875): #6      _ConfigScreenState.getUserToken (package:optimo_offline/screens/config_screen.dart:267:31)
E/flutter (27875): <asynchronous suspension>
E/flutter (27875): #7      _ConfigScreenState.build.<anonymous closure> (package:optimo_offline/screens/config_screen.dart:192:25)
E/flutter (27875): #8      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:635:14)
E/flutter (27875): #9      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:711:32)
E/flutter (27875): #10     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (27875): #11     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
E/flutter (27875): #12     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:275:7)
E/flutter (27875): #13     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:455:9)
E/flutter (27875): #14     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:75:13)
E/flutter (27875): #15     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:102:11)
E/flutter (27875): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (27875): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (27875): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (27875): #19     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (27875): #20     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (27875): #21     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (27875): #22     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (27875): #23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (27875): #24     _invoke1 (dart:ui/hooks.dart:250:10)
E/flutter (27875): #25     _dispatchPointerDataPacket (dart:ui/hooks.dart:159:5)
```
No exception text, no error message, no response. I have two APIs and first one works fine but second doesn't. The only different between them is url. 
Example url (fake ones) to show a difference:
working one: http://api.troncomputers.pl/api/data
not working one: https://api.tron-computers/api/data

I'm sure that this is not a `https` vs `http` issue. I've checked with fake API without `-` character in url and works fine.
ver. `http: ^0.12.0+2`

**Comment by natebosch** [comment]
It looks like this would be caused by an `HttpException` with a blank message.
https://github.com/dart-lang/http/blob/7774121a406fedb0502fce7cc224476c1ac78469/lib/src/io_client.dart#L65

Can you check how these requests behave when you use the SDK classes from `dart:io` directly instead of going through this package? It's likely we need to find what causes the exception with a blank `message` and fix that in the SDK...

**Comment by troncomputers** [comment]
I'm not sure if I'm doing it right. This is the code I used:
```dart
    HttpClient client = HttpClient();
    client.getUrl(Uri.parse(panelUrl)).then((HttpClientRequest request) {
      return request.close();
    }).then((HttpClientResponse response) {
      response.transform(utf8.decoder).listen((contents) {
        print(contents);
      });
    });
```
Exception I get:
```
E/flutter ( 5121): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: HttpException: , uri = https://api.tron-computers/api/data/getzadaniaopiekuna
E/flutter ( 5121): null
```
I should get StatusCode 401 Unauthorized. 
Do you really need the correct API url for debugging? I am not quite sure about security with putting that here.
🤔

**Comment by cskau-g** [comment]
Unless you have some unusual DNS setup on your network and/or device, that is expected to fail with a DNS resolve error since `api.tron-computers` is not a valid address.
No request will be sent to your server, and no 401 will be returned.

**Comment by troncomputers** [comment]
The API is behind an Angular website. The whole project is Angular + .NET Core API but I need to connect to that API with Android app. I can open an Angular website on emulator and everything is fine and working great. The HttpException is thrown on emulator and on normal device through WIFI and LTE. If an URL is not valid I'm getting:
```
E/flutter (10528): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: SocketException: Failed host lookup: 'api.tron-computers' (OS Error: No address associated with hostname, errno = 7)
E/flutter (10528): null
```
I didn't specified any custom DNS configuration on any devices.
I've tested on [ApiTester](https://apitester.com/) and I'm getting `HTTP/1.1 401 Unauthorized`

**Comment by natebosch** [comment]
The troubling part here is `Unhandled Exception: HttpException: ,`

For some reason the `message` is blank.

https://github.com/dart-lang/sdk/blob/782243640b6939e76dc57e970de9d99a1e439fc4/sdk/lib/_http/http.dart#L2179

I'll transfer this to the SDK repo since the underlying problem is somewhere in the http handling.
