### ISSUE TITLE
Invalid header field name, with 44

### ISSUE THREAD

**Issue by zxy888** [dart-lang/http#460]
I report this exception when I use the following request：

    final http.Response response = await http.get(
      url,
      headers: <String,String>{
        HttpHeaders.contentTypeHeader: 'application/json; charset=UTF-8',
        HttpHeaders.authorizationHeader:"Bearer " + token,
       },
    );
    print('response=' + response.body);

[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: Invalid header field name, with 44
#0      IOClient.send (package:http/src/io_client.dart:62:7)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:91:38)
#2      BaseClient.get (package:http/src/base_client.dart:27:7)
#3      get.<anonymous closure> (package:http/http.dart:46:36)

**Comment by valehasadli** [comment]
Hi @zxy888, please check this [issue](https://github.com/dart-lang/http/issues/416)

Please, share more related code statements.

**Comment by brianquinlan** [comment]
There is not enough context to debug this. Could you provide a complete reproduction example.
