### ISSUE TITLE
Unhandled exception: NoSuchMethodError: The getter 'length' was called on null. Receiver: null Tried calling: length

### ISSUE THREAD

**Issue by ArpanBhavsar** [dart-lang/http#492]
On passing null value in map it stops the request and show an unhandled exception.

```
Unhandled exception:
NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length
#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:51:5)
#1      _Uri._uriEncode  (dart:core-patch/uri_patch.dart:44:23)
#2      Uri.encodeQueryComponent  (dart:core/uri.dart:1103:17)
#3      mapToQuery.<anonymous closure> 
package:http/src/utils.dart:19
#4      CastMap.forEach.<anonymous closure>  (dart:_internal/cast.dart:288:8)
#5      _LinkedHashMapMixin.forEach  (dart:collection-patch/compact_hash.dart:377:8)
#6      CastMap.forEach  (dart:_internal/cast.dart:287:13)
#7      mapToQuery 
package:http/src/utils.dart:17
#8      Request.bodyFields= 
package:http/src/request.dart:137
#9      BaseClient._sendUnstreamed 
package:http/src/base_client.dart:85
#10     BaseClient.post 
package:http/src/base_client.dart:32
#11     post.<anonymous closure> 
package:http/http.dart:70
#12     _withClient 
package:http/http.dart:166
```

 It should show user that they have to handle that exception or else the null value should be set to any default value like ''.

**Comment by natebosch** [comment]
I think nulls are best handled by the calling code, especially following the null safety migration. Here is a snippet that can handle the fallback if you need it:

```dart
Map<String, String> defaultNulls(Map<String, String> original) =>
    {for (var key in original.keys) key: original[key] ?? ''};
```
