### ISSUE TITLE
url size limitation

### ISSUE THREAD

**Issue by lejard-h** [dart-lang/http#50]
Reproduce

```dart
import 'package:http/http.dart';

main() {
  Client client = new IOClient();
  String str = "a" * 10000;
  client.post("http://localhost:1338/$str").then((Response res) {
    print(res.statusCode);
    print(res.body);
    client.close();
  }, onError: (error) {
    print(error);
    client.close();
  });
}
```

`nc -l 1338`

I am getting this error but I cannot catch it.

```dart
Unhandled exception:
HttpException: Headers size exceeded the of '8192' bytes
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1138)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

Is it the correct behaviour, I am dealing with an api that need a lot of data in the url, any workaround ?

**Comment by nex3** [comment]
There's no check for this in http, so I think this is a `dart:io` issue.

**Comment by nex3** [comment]
This issue was moved to dart-lang/sdk#28251
