### ISSUE TITLE
Error - Unhandled Exception: HttpException: Unexpected response (unsolicited response without request)

### ISSUE THREAD

**Issue by shashank-gb** [dart-lang/http#558]
I'm having an issue while making an HTTP post request in order to send the data to My SQL via php as an API. 

**Small Piece of Code**

```
Future userRegistration() async {
    String name = nameController.text;
    String email = emailController.text;
    String password = passwordController.text;

    var url = Uri.parse('http://pro-connect.infinityfreeapp.com/register_user.php');

    var response = await http.post(url, body: {'name': name, 'email': email, 'password': password});

    var message = '${response.body}';

    print(message);
}
```

**ERROR**

```
E/flutter (14533): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: HttpException: Unexpected response (unsolicited response without request).
E/flutter (14533): #0      new _HttpClientConnection.<anonymous closure> (dart:_http/http_impl.dart:1824:9)
E/flutter (14533): #1      _rootRunUnary (dart:async/zone.dart:1362:47)
E/flutter (14533): #2      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter (14533): #3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
E/flutter (14533): #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (14533): #5      _DelayedData.perform (dart:async/stream_impl.dart:591:14)
E/flutter (14533): #6      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
E/flutter (14533): #7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
E/flutter (14533): #8      _rootRun (dart:async/zone.dart:1346:47)
E/flutter (14533): #9      _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (14533): #10     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter (14533): #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
E/flutter (14533): #12     _rootRun (dart:async/zone.dart:1354:13)
E/flutter (14533): #13     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (14533): #14     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter (14533): #15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
E/flutter (14533): #16     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (14533): #17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

**flutter doctor log**
```
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.746], locale en-IN)
    • Flutter version 2.0.5 at C:\src\flutter
    • Framework revision adc687823a (4 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\SHASHANKgb\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files (x86)\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\SHASHANKgb\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • RMX1992 (mobile) • afc22e82 • android-arm64  • Android 10 (API 29)
    • Chrome (web)     • chrome   • web-javascript • Google Chrome 90.0.4430.72
    • Edge (web)       • edge     • web-javascript • Microsoft Edge 89.0.774.63

• No issues found!
```

**Note** : I am running this application in mobile device

**Comment by AANikolaev** [comment]
+1

**Comment by natebosch** [comment]
This is unrelated to `package:http`. It looks like this error is coming from the SDK.
