### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by NadieFiind** [dart-lang/http#580]
Doing a `put` request throws a `Null check operator used on a null value` error on my machine. But when I tried to run the same code on Replit it worked fine.

```dart
await http.Client().put(
	Uri.parse("https://jsonplaceholder.typicode.com/todos"),
	headers: {"Content-type": "application/json; charset=UTF-8"},
	body: json.encode({
		"userId": 1,
		"id": 1,
		"title": "delectus aut autem",
		"completed": false
	})
);
```

```bash
Unhandled exception:
Null check operator used on a null value
#0      IOClient.send (package:http/src/io_client.dart:30:36)
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:38)
#2      BaseClient.put (package:http/src/base_client.dart:37:7)
```

**Comment by natebosch** [comment]
This could happen if you had called `close()` on that client before making the request. If you have a consistent repro that doesn't involve calling `close()` we can investigate further.
