### ISSUE TITLE
Should streamed_request_test.dart run?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/http#6]
I'm working on a package that includes a transformer (Reflectable), so I need to run tests that have been transformed.  The situation is very similar to that of http/build/test/io/streamed_request_test.dart.  

However, I have the problem that the build/... tree does not contain 'packages' directories (nor symlinks) in nested directories, only in build/test.  This makes the tests fail in Reflectable, so I wondered why streamed_request_test.dart does _not_ fail in http (http is not red on the package-bots).  I cannot see any reason in http/.status why this test should not run, and it does indeed fail when I 'git clone' the http package, 'pub get', 'pub build --mode=debug test', and run this:

```
~/tmp/tmprepos/http(master)$ dart test/io/streamed_request_test.dart    [15:12]
unittest-suite-wait-for-done
PASS: contentLength controls the Content-Length header
PASS: contentLength defaults to sending no Content-Length
PASS: .send() with a response with no content length

All 3 tests passed.
unittest-suite-success
~/tmp/tmprepos/http(master)$ dart build/test/io/streamed_request_test.dart
Unhandled exception:
Uncaught Error: Load Error: FileSystemException: Cannot open file, path = '/usr/local/google/home/eernst/tmp/tmprepos/http/build/test/io/packages/http/http.dart' (OS Error: No such file or directory, errno = 2)
Stack Trace:
#0      _asyncLoadErrorCallback (dart:_builtin:335)
#1      _asyncLoadError (dart:_builtin:354)
#2      _loadDataAsyncDartIO.<anonymous closure> (dart:_builtin:76)
#3      _RootZone.runUnary (dart:async/zone.dart:1155)
#4      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:515)
#5      _Future._propagateToListeners (dart:async/future_impl.dart:570)
#6      _Future._completeWithValue (dart:async/future_impl.dart:358)
#7      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:412)
#8      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#9      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#10     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:886)
#1      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#2      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)
```

So I was wondering:  Is it a bug that this test (build/test/io/streamed_request_test.dart) is never executed, or does it somehow run successfully on the package bots?  In the latter case, I'd like to know how you do it, and in the former case you might want to check it out.  ;-)

I've notified the pub-dartlang folks on https://code.google.com/p/dart/issues/detail?id=22677.

**Comment by eernstg** [comment]
Issue resolved, my bad:  In spite of several attempts to reproduce the way tests are executed on the package-bots, there was an inconsistency:  The runs there _do_ get a `--package-root` option, so they don't need those nested `packages` directories, and the package-bots _do_ execute the test I mentioned, successfully.
