### ISSUE TITLE
GET works but flutter throw an error

### ISSUE THREAD

**Issue by Alkabann** [dart-lang/http#850]
I'm doing a simple http request (http.get(uri, headers: _headers)
 I have differents errors:

`Software caused connection abort`

`Bad file descriptor`

`Failed to parse header value`

`Failed host lookup: 'xxxxxxxx.execute-api.eu-west-3.amazonaws.com'`

Here is the stacktrace (always the same for differents errors).

```
#0 IOClient.send (package:http/src/io_client.dart:90)
<asynchronous suspension>
#1 BaseClient._sendUnstreamed (package:http/src/base_client.dart:93)
<asynchronous suspension>
#2 _withClient (package:http/http.dart:164)
<asynchronous suspension>
```
the call is successful, but Flutter throw an error.

My guess is that the user have a bad connection, Flutter think the call failed but actually, the call was successful.

**Comment by Alkabann** [comment]
I still have errors spamming me on my dev env with my clients. 
I still haven't found better way than just ignoring them for the moment (because it's not blocking).
Anyone has an idea or the same problem ?

**Comment by brianquinlan** [comment]
This doesn't seem related to `cupertino_http` - use are using the `dart:io` HTTP client implementation.

Do you see the same issue if you try to do this using `curl` or a similar tool? On what platform do you get this error? 

Here are our recommended diagnostic steps:

Note that a failing HTTP connection is almost certainly not caused by a bug in
package:http.

This package is a wrapper around the HttpClient from dart:io and HttpRequest
from dart:html. Before filing a bug here verify that the issue is not surfaced
when using those interfaces directly.

https://api.dart.dev/stable/dart-io/HttpClient-class.html
https://api.dart.dev/stable/dart-html/HttpRequest-class.html

# Common problems:

- A security policy prevents the connection.
- Running in an emulator that does not have outside internet access.
- Using Android and not requesting internet access in the manifest.
  https://github.com/flutter/flutter/issues/29688

None of these problems are influenced by the code in this repo.

# Diagnosing:

- Attempt the request outside of Dart, for instance in a browser or with `curl`.
- Attempt the request with the dart:io or dart:html equivalent code paths.

**Comment by tulioccalazans** [comment]
Same issue here!
