### ISSUE TITLE
Unhandled exception that can never be handled

### ISSUE THREAD

**Issue by Hamada-Gado** [dart-lang/http#872]
# The issue
 I want to get data from two APIs so I call the two methods that return future and then await for their return value so that I don't wait if one takes too long. When I try to handle SocketException (no internet) from http.get() in the async function an unhandled exception still occurs breaking the program the exception is `Exception has occurred. _ClientSocketException (Failed host lookup: 'APIs BASE_URL') from io_cleint.dart`, and this another traceback from the terminal
```E/flutter (16549): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Failed host lookup: 'cat-fact.herokuapp.com'
E/flutter (16549): #0      IOClient.send (package:http/src/io_client.dart:88:7)
E/flutter (16549): <asynchronous suspension>
E/flutter (16549): #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:32)
E/flutter (16549): <asynchronous suspension>
E/flutter (16549): #2      _withClient (package:http/http.dart:164:12)
E/flutter (16549): <asynchronous suspension>
```

# How to reproduce it.
The code below was refactored to catch any thing because after hours and hours of debugging not figuring out why on SocketException wasn't working I tried to catch any exception and seeing it

## home_page.dart
```  Future<void> setRandomImageAndFact() async {
    setState(() {
      json = imageBytes = null;
    });

    Future<Uint8List> bytesImageFuture = getRandomImage();
    Future<Map<String, dynamic>> decodedJsonFuture = getRandomFact();

    try{
      imageBytes = await bytesImageFuture;
      json = await decodedJsonFuture;
    } catch (e) {
      print(e);
      print(e.runtimeType);
      socketException = true;
    }

    setState(() {});
  }
```

## images.dart
```Future<Uint8List> getRandomImage() async {
  Uri url = Uri.https(BASE_URL, "cat");

  http.Response response;

  try {
    response = await http.get(url);
  } catch (_){
    return UintList(0);
  }

  if (response.statusCode == 200) {
    return response.bodyBytes;
  }

  throw Exception("Could not get random image ${response.statusCode}");
}
```

## facts.dart
```Future<Map<String, dynamic>> getRandomFact() async {
  Uri url = Uri.https(BASE_URL, "facts/random");
  Future<http.Response> responseFuture = http.get(url);
  Future<List<String>> rejectedListFuture = loadPrefs(Mode.rejected.value);

  List<String> rejectedList = await rejectedListFuture;
  http.Response response;

  try {
    response = await responseFuture;
  } catch (_){
    return {};
  }

  if (response.statusCode == 200) {
    Map<String, dynamic> decodedJson = jsonDecode(response.body);
    if (rejectedList.every((element) => element != decodedJson['_id'])) {
      return decodedJson;
    } else {
      return getRandomFact();
    }
  }

  throw Exception("Could not get random fact ${response.statusCode}");
}
```
# What I possibly found
I believe I might have figured out the problem. If you look at the traceback from the terminal it seems that the file http.dart in line 164 in the function _withClient<T> their is a try-finally block with no catch and for some reason, my code is not reciving any exceptions that come from this function the source of the error is this file alone it is not even showing which of the two functions I wrote is calling this method. This seems to be related to it being async and that my methods already return a value after handling any exceptions. I don't have a deep understanding of the http module or async in dart, so if my assumptions are wrong and I am the one that wrote this code in a wried way I hope you can help me in using this module the right way.
```
Future<T> _withClient<T>(Future<T> Function(Client) fn) async {
  var client = Client();
  try {
    return await fn(client);
  } finally {
    client.close();
  }
}
```

# One more thing
I am not sure if this should be a separate issue or a question on StackOverflow [I actually have already asked and this is the link to it](https://stackoverflow.com/questions/75440435/cant-catching-two-awaits-in-dart-fluttter-http-module), but as I said before the above could was changed a little bit. Previously my two methods to return data from the APIs would rethrow the SocketException so that if either of them had a problem but not the other I would know but this seems to also cause a problem like the try-catch block catch the on SocketException from one of them but not the other since it already caught I guess. Therefore is it wrong to rethrow the same error inside one try-catch. But even if I gave them separate try-catch an error still occurs. Honestly, I am tired, I tried a lot of things that I became confused by all the combinations I tried. I hope someone can help. Thanks in advance.

**Comment by Jangberry** [comment]
I'm having the same issue and I even tried a workaround that doesn't work : 
The following code
```dart
http.Response res;
try {
    print('try');
    res = await http.get(Uri.parse('<some url refused somehow>'));
    print('success');
} catch (e) { // FIXME: 'failed to lookup host' isn't catched here
    print('yay error');
    rethrow;
} finally {
    print('hello');
}
print('wait...');
```
only prints `try` and doesn't throw anyting. The debugger really sees the error in the dart io files but (due to async gaps ?) the callstack doesn't trace back to http/my code. And step by step execution really reveals that the error happens `res = await http.get(...);`

**Comment by larssn** [comment]
@Hamada-Gado No, finally will always run. So you can cross that idea off. 🙂

You can try it yourself:
```dart
void main() {
  try {
    throw Exception('Ded');
  } finally {
    print('Clean up');
  }
}

```
