### ISSUE TITLE
Http package refused connection on mobile network many time but on wifi works fine after updating http package

### ISSUE THREAD

**Issue by ankittripathi786** [dart-lang/http#892]
E/flutter (25854): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Connection refused
E/flutter (25854): #0      IOClient.send (package:http/src/io_client.dart:88:7)
E/flutter (25854): <asynchronous suspension>
E/flutter (25854): #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:32)
E/flutter (25854): <asynchronous suspension>
E/flutter (25854): #2      _withClient (package:http/http.dart:164:12)
E/flutter (25854): <asynchronous suspension>
E/flutter (25854): #3      _SuperDistributorScreenState.build.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:financepe_master/modules/super_distributor/views/super_distributor_screen.dart:581:69)
E/flutter (25854): <asynchronous suspension>
E/flutter (25854):

**Comment by ankittripathi786** [comment]
my whole team team face this problem in our retailer app api works slowly on mobile network but on wifi works superb. it is not api problem http package have some kind of issue. please help to rectify this problem as much as possible.

**Comment by mittalsam98** [comment]
I was also facing same issue @ankittripathi786 (working fine on wifi but not getting anything on mobile data), did u find any solution?

**Comment by ankittripathi786** [comment]
> I was also facing same issue @ankittripathi786 (working fine on wifi but not getting anything on mobile data), did u find any solution?
> 

No buddy... Dio and get also facing same issues

**Comment by ankittripathi786** [comment]
> > I was also facing same issue @ankittripathi786 (working fine on wifi but not getting anything on mobile data), did u find any solution?
> > 
> 
> No buddy... Dio and get also facing same issues 

I tried all of them

**Comment by ankxz** [comment]
Did someone find any solution?

**Comment by ankittripathi786** [comment]
No buddy this problem from Google side http package is problem

**Comment by aliaafreen** [comment]
have anyone got any solution about this?
